// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysuserservice.proto

package cn.zjhn.api.sysuserservice.protobuf.dubbo;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SysUsers user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.SysUsers user = 1;</code>
   * @return The user.
   */
  cn.zjhn.SysUsers getUser();
  /**
   * <code>.SysUsers user = 1;</code>
   */
  cn.zjhn.SysUsersOrBuilder getUserOrBuilder();
}
