// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysuserservice.proto

package cn.zjhn.api.sysuserservice.protobuf.dubbo;

public interface AddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 row = 1;</code>
   * @return The row.
   */
  int getRow();
}
