// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysuserservice.proto

package cn.zjhn.api.sysuserservice.protobuf.dubbo;

public interface dateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:date)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 y = 1;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 m = 2;</code>
   * @return The m.
   */
  int getM();

  /**
   * <code>int32 d = 3;</code>
   * @return The d.
   */
  int getD();
}
