// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysuserservice.proto

package cn.zjhn.api.sysuserservice.protobuf.dubbo;

public interface streamselectUserListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamselectUserListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .SysUsers user = 1;</code>
   */
  java.util.List<cn.zjhn.SysUsers> 
      getUserList();
  /**
   * <code>repeated .SysUsers user = 1;</code>
   */
  cn.zjhn.SysUsers getUser(int index);
  /**
   * <code>repeated .SysUsers user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .SysUsers user = 1;</code>
   */
  java.util.List<? extends cn.zjhn.SysUsersOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .SysUsers user = 1;</code>
   */
  cn.zjhn.SysUsersOrBuilder getUserOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <code>int32 page = 3;</code>
   * @return The page.
   */
  int getPage();
}
