// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysuserservice.proto

package cn.zjhn.api.sysuserservice.protobuf.dubbo;

public interface SysUsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SysUsers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 deptid = 4;</code>
   * @return The deptid.
   */
  int getDeptid();

  /**
   * <code>string phone = 5;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 5;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string identityCard = 6;</code>
   * @return The identityCard.
   */
  java.lang.String getIdentityCard();
  /**
   * <code>string identityCard = 6;</code>
   * @return The bytes for identityCard.
   */
  com.google.protobuf.ByteString
      getIdentityCardBytes();

  /**
   * <code>string identityCardAddress = 7;</code>
   * @return The identityCardAddress.
   */
  java.lang.String getIdentityCardAddress();
  /**
   * <code>string identityCardAddress = 7;</code>
   * @return The bytes for identityCardAddress.
   */
  com.google.protobuf.ByteString
      getIdentityCardAddressBytes();

  /**
   * <code>string nation = 8;</code>
   * @return The nation.
   */
  java.lang.String getNation();
  /**
   * <code>string nation = 8;</code>
   * @return The bytes for nation.
   */
  com.google.protobuf.ByteString
      getNationBytes();

  /**
   * <code>string nativePlace = 9;</code>
   * @return The nativePlace.
   */
  java.lang.String getNativePlace();
  /**
   * <code>string nativePlace = 9;</code>
   * @return The bytes for nativePlace.
   */
  com.google.protobuf.ByteString
      getNativePlaceBytes();

  /**
   * <code>bool sex = 10;</code>
   * @return The sex.
   */
  boolean getSex();

  /**
   * <code>bool isAttendance = 11;</code>
   * @return The isAttendance.
   */
  boolean getIsAttendance();

  /**
   * <code>string titles = 12;</code>
   * @return The titles.
   */
  java.lang.String getTitles();
  /**
   * <code>string titles = 12;</code>
   * @return The bytes for titles.
   */
  com.google.protobuf.ByteString
      getTitlesBytes();

  /**
   * <code>int32 eeState = 13;</code>
   * @return The eeState.
   */
  int getEeState();

  /**
   * <code>.date birthday = 14;</code>
   * @return Whether the birthday field is set.
   */
  boolean hasBirthday();
  /**
   * <code>.date birthday = 14;</code>
   * @return The birthday.
   */
  date getBirthday();
  /**
   * <code>.date birthday = 14;</code>
   */
  dateOrBuilder getBirthdayOrBuilder();

  /**
   * <code>string registeredResidence = 15;</code>
   * @return The registeredResidence.
   */
  java.lang.String getRegisteredResidence();
  /**
   * <code>string registeredResidence = 15;</code>
   * @return The bytes for registeredResidence.
   */
  com.google.protobuf.ByteString
      getRegisteredResidenceBytes();

  /**
   * <code>string politicalOutlook = 16;</code>
   * @return The politicalOutlook.
   */
  java.lang.String getPoliticalOutlook();
  /**
   * <code>string politicalOutlook = 16;</code>
   * @return The bytes for politicalOutlook.
   */
  com.google.protobuf.ByteString
      getPoliticalOutlookBytes();

  /**
   * <code>string address = 17;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 17;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string emergencyContact = 18;</code>
   * @return The emergencyContact.
   */
  java.lang.String getEmergencyContact();
  /**
   * <code>string emergencyContact = 18;</code>
   * @return The bytes for emergencyContact.
   */
  com.google.protobuf.ByteString
      getEmergencyContactBytes();

  /**
   * <code>bool maritalStatus = 19;</code>
   * @return The maritalStatus.
   */
  boolean getMaritalStatus();

  /**
   * <code>string contactRelationship = 20;</code>
   * @return The contactRelationship.
   */
  java.lang.String getContactRelationship();
  /**
   * <code>string contactRelationship = 20;</code>
   * @return The bytes for contactRelationship.
   */
  com.google.protobuf.ByteString
      getContactRelationshipBytes();

  /**
   * <code>string bankCard = 21;</code>
   * @return The bankCard.
   */
  java.lang.String getBankCard();
  /**
   * <code>string bankCard = 21;</code>
   * @return The bytes for bankCard.
   */
  com.google.protobuf.ByteString
      getBankCardBytes();

  /**
   * <code>int32 contactNumber = 22;</code>
   * @return The contactNumber.
   */
  int getContactNumber();

  /**
   * <code>string education = 23;</code>
   * @return The education.
   */
  java.lang.String getEducation();
  /**
   * <code>string education = 23;</code>
   * @return The bytes for education.
   */
  com.google.protobuf.ByteString
      getEducationBytes();

  /**
   * <code>string academicDegree = 24;</code>
   * @return The academicDegree.
   */
  java.lang.String getAcademicDegree();
  /**
   * <code>string academicDegree = 24;</code>
   * @return The bytes for academicDegree.
   */
  com.google.protobuf.ByteString
      getAcademicDegreeBytes();

  /**
   * <code>string graduationSchool = 25;</code>
   * @return The graduationSchool.
   */
  java.lang.String getGraduationSchool();
  /**
   * <code>string graduationSchool = 25;</code>
   * @return The bytes for graduationSchool.
   */
  com.google.protobuf.ByteString
      getGraduationSchoolBytes();

  /**
   * <code>string major = 26;</code>
   * @return The major.
   */
  java.lang.String getMajor();
  /**
   * <code>string major = 26;</code>
   * @return The bytes for major.
   */
  com.google.protobuf.ByteString
      getMajorBytes();

  /**
   * <code>string mailbox = 27;</code>
   * @return The mailbox.
   */
  java.lang.String getMailbox();
  /**
   * <code>string mailbox = 27;</code>
   * @return The bytes for mailbox.
   */
  com.google.protobuf.ByteString
      getMailboxBytes();

  /**
   * <code>.date entryTime = 28;</code>
   * @return Whether the entryTime field is set.
   */
  boolean hasEntryTime();
  /**
   * <code>.date entryTime = 28;</code>
   * @return The entryTime.
   */
  cn.zjhn.date getEntryTime();
  /**
   * <code>.date entryTime = 28;</code>
   */
  cn.zjhn.dateOrBuilder getEntryTimeOrBuilder();

  /**
   * <code>.date contractCommencement = 29;</code>
   * @return Whether the contractCommencement field is set.
   */
  boolean hasContractCommencement();
  /**
   * <code>.date contractCommencement = 29;</code>
   * @return The contractCommencement.
   */
  cn.zjhn.date getContractCommencement();
  /**
   * <code>.date contractCommencement = 29;</code>
   */
  cn.zjhn.dateOrBuilder getContractCommencementOrBuilder();

  /**
   * <code>.date contractEnd = 30;</code>
   * @return Whether the contractEnd field is set.
   */
  boolean hasContractEnd();
  /**
   * <code>.date contractEnd = 30;</code>
   * @return The contractEnd.
   */
  cn.zjhn.date getContractEnd();
  /**
   * <code>.date contractEnd = 30;</code>
   */
  cn.zjhn.dateOrBuilder getContractEndOrBuilder();

  /**
   * <code>.date trialStart = 31;</code>
   * @return Whether the trialStart field is set.
   */
  boolean hasTrialStart();
  /**
   * <code>.date trialStart = 31;</code>
   * @return The trialStart.
   */
  cn.zjhn.date getTrialStart();
  /**
   * <code>.date trialStart = 31;</code>
   */
  cn.zjhn.dateOrBuilder getTrialStartOrBuilder();

  /**
   * <code>.date trialEnd = 32;</code>
   * @return Whether the trialEnd field is set.
   */
  boolean hasTrialEnd();
  /**
   * <code>.date trialEnd = 32;</code>
   * @return The trialEnd.
   */
  cn.zjhn.date getTrialEnd();
  /**
   * <code>.date trialEnd = 32;</code>
   */
  cn.zjhn.dateOrBuilder getTrialEndOrBuilder();

  /**
   * <code>.date terminationTime = 33;</code>
   * @return Whether the terminationTime field is set.
   */
  boolean hasTerminationTime();
  /**
   * <code>.date terminationTime = 33;</code>
   * @return The terminationTime.
   */
  cn.zjhn.date getTerminationTime();
  /**
   * <code>.date terminationTime = 33;</code>
   */
  cn.zjhn.dateOrBuilder getTerminationTimeOrBuilder();

  /**
   * <code>string remark = 34;</code>
   * @return The remark.
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 34;</code>
   * @return The bytes for remark.
   */
  com.google.protobuf.ByteString
      getRemarkBytes();

  /**
   * <code>.date createTime = 35;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.date createTime = 35;</code>
   * @return The createTime.
   */
  cn.zjhn.date getCreateTime();
  /**
   * <code>.date createTime = 35;</code>
   */
  cn.zjhn.dateOrBuilder getCreateTimeOrBuilder();
}
